### ISSUE TITLE
error setting up integration

### ISSUE THREAD

**Issue by insipiens** [geustace/home-assistant-enasolar#1]
Hi Glenn,

I tried setting up this for an Enasolar GT series inverter

When I got to entering the IP address it errored out. Below are some screenshots.

![image](https://github.com/geustace/home-assistant-enasolar/assets/68975498/76c5a954-b549-478b-8d35-52ed8f3dd8aa)

The Home assistant log showed this detail:
![image](https://github.com/geustace/home-assistant-enasolar/assets/68975498/a73a7546-71d4-4698-af4f-cae83d8f3ff4)

some details about the installation.

- enasolar set up with lan static ip address and default settings
- home assistant running on proxmox as home-assistant core , so running in a docker container.
 version:  Home Assistant 2023.8.4 Supervisor 2023.08.1 Operating System 10.5 Frontend 20230802.1 - latest , and python3
- installed the repo via HACS custom repo facility

Looking forward to any insight you can provide.

Cheers

John

**Comment by geustace** [comment]
Latest changes are now all working correctly on 2023.08.2, so if you can provide the html from your inverter's settings.html page I can work on that next.
http://inverter.ip/settings.html, the if you can do view source in your browser, cut and past the html and attach to a message.  I can then try to work out how to pickup the correct numbers.

**Comment by geustace** [comment]
There is a long line of inline javascript at about line 12 of the HTML, this is the one I really need as the serial number in my version of the firmware is constructed as follows
var b=(Number(("19065")*65536)+Number("44487")).toString(10);
If the code in your case it different, the webpage version is not 25, I'll need to poke around a bit for it.

**Comment by geustace** [comment]
I have updated pyenasolar to use a fictitious serial number if the web page version isnt 25.  You will need to redownload from HACS and restart HA.

**Comment by insipiens** [comment]
Hi Glen

Thanks for that.

The new integration doesn't work either but I noted the html is different to the suggestion you advised. Perhaps this model GT2000 is substantially different?

Attached is the settings.html (zipped as html can't be loaded)
[enasolarsettings.zip](https://github.com/geustace/home-assistant-enasolar/files/12521784/enasolarsettings.zip)

**Comment by geustace** [comment]
That web page is nothing like mine :-( , It also has the title Solar Shed, which implies it may be a rebranded version.  I would really like to get this to work for you, are you ok with helping?  Can you check out whether the following URLs are available from the web interface

http://inverter/meters.xml
http://inverter/data.xml
http://inverter/wv.txt
