### ISSUE TITLE
Web Page Version 26

### ISSUE THREAD

**Issue by bigwave** [geustace/home-assistant-enasolar#2]
I'm trying to add two EnaSolar inverters with Web Page Version 26, the first to be added seems to work, but the second one fails with "Device is already configured" error. 

> There is a long line of inline javascript at about line 12 of the HTML, this is the one I really need as the serial number in my version of the firmware is constructed as follows
> `var b=(Number(("19065")*65536)+Number("44487")).toString(10);`
> If the code in your case it different, the webpage version is not 25, I'll need to poke around a bit for it.
> 

_Originally posted by @geustace in https://github.com/geustace/home-assistant-enasolar/issues/1#issuecomment-1704427934_

The code on "Web Page Version 26" is the same format as above:
`var b = (Number(("21478") * 65536) + Number("5963")).toString(10);`
but is excluded by line 255
`if self.webpage_version == 25:`

Running pyensolar library directly gives 
```
(venv) ➜  venv python lib/python3.11/site-packages/pyenasolar/__init__.py
(venv) ➜  venv cat pyenasolar.log 
INFO:root:Started
DEBUG:__main__:Attempt to determine the Inverter's Serial No.
DEBUG:__main__:Webpage Version: 26
DEBUG:__main__:Unknown Webpage Version
DEBUG:__main__:Attempt to determine Inverter model setup and capabilities
DEBUG:__main__:Found: CAP=0, DC=1, Max=2.0
INFO:root:Finished
```

**Comment by geustace** [comment]
I have updated the pyenasolar module to include version 26. I only have the one inverter so may not have implemented things correctly to support two.  I'll have to have a look at the code.

**Comment by bigwave** [comment]
Thanks, that's it working. 

![image](https://github.com/geustace/home-assistant-enasolar/assets/693474/9675eec1-e24e-4917-b5df-1726213532d1)
Turbine 2 is off at the moment due to low water level :-(
