### ISSUE TITLE
error setting up integration

### ISSUE THREAD

**Issue by bashers222** [geustace/home-assistant-enasolar#5]
Hi, as per the first issue logged (https://github.com/geustace/home-assistant-enasolar/issues/1) , i seem to have another version that is not supported by this HACS integration and I'd love to get this integrated

I'm seeing the folloiwing in the debug logs:
`2024-06-25 20:38:03.137 ERROR (MainThread) [custom_components.enasolar.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/enasolar/config_flow.py", line 70, in _try_connect
    await self._enasolar.interogate_inverter(host)
  File "/usr/local/lib/python3.12/site-packages/pyenasolar/__init__.py", line 301, in interogate_inverter
    self.capability = int(cap[0])`

As suggested, ive added the settings file to see if that helps
[enasolar.txt](https://github.com/user-attachments/files/15977591/enasolar.txt)

**Comment by geustace** [comment]
I now get why web scrapping is not allowed in the core integrations. Unfortunately there is no API for these inverters so there isnt an alternative. I'll have a look at this and get back to you. BTW: Thanks for including the Settings page it should help.

**Comment by bashers222** [comment]
Thanks for your assistance

**Comment by geustace** [comment]
Can you please upload the wv.txt we page from the inverter. http://inverter/wv.txt, actually just confirm that is it 21

**Comment by geustace** [comment]
Digging around in the code, I need some of the text in the index.html page.  Can you browse to it, show source then copy and paste just the &lt;head&gt;...&lt;/head&gt; section as it has the jscript in it that I need to parse. Thanks

**Comment by bashers222** [comment]
yep, its 21
[enasolar-index.txt](https://github.com/user-attachments/files/15995160/enasolar-index.txt)

**Comment by bashers222** [comment]
`<html>
<body>

<head id='head'>
--
  | <title>EnaSolar Inverter</title>
  | 
  | <meta name="splash" content="Enasolar Inverter">
  | <style type="text/css">body,td,input,select{font-family:Tahoma,Verdana,Arial,Helvetica,sans-serif;font-size:9pt}body{margin:0}table{margin:0;padding:0;border:0;border-collapse:collapse}td{white-space:nowrap;border:0;margin:0;padding:1px}td,th{display:table-cell;vertical-align:inherit}h2{margin:0;color:#73a13f;font-size:12pt;width:214px;height:23px}.style2{width:150px}td.Reading{width:100px;font-weight:bold;text-align:right}.graph_title{font-size:12pt;font-weight:bold;text-align:center;color:#73a13f}.graph_y_label{font-size:8pt;text-align:right;color:#73a13f}#menu{padding:0;margin:12px 0}#menu li{list-style:none outside none;height:28px}#menu li a{color:#fff;font-size:17px;font-weight:bold;text-decoration:none}#menu li a:hover{text-decoration:underline}.meter_reading{font-size:20pt;text-align:left;padding-left:25px}</style>
  | <script src="//ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript"></script>
  | 
  | <script type="text/javascript">
  | var tiv="Enasolar-Garden";if(tiv!=""){document.title=tiv};
  | var globalWdtI;var gMt;function iready(){var a="3";var c="<br/><table style='width: 100%;' cellspacing='10px'>";c+="<tr><td>Utilisation:</td></tr>";c+="<tr><td><div class='meter_reading' id='utilisation'></div></td></tr>";c+="<tr><td>Output Power:</td></tr>";c+="<tr><td><div class='meter_reading' id='output_power'></div></td></tr>";if(has2mpp(a)){c+="<tr><td>Input Voltage 1:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage'></div></td></tr>";c+="<tr><td>Input Voltage 2:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage2'></div></td></tr>"}else{c+="<tr><td>Input Voltage:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage'></div></td></tr>"}c+="<tr><td>Output Voltage:</td></tr>";c+="<tr><td><div class='meter_reading' id='output_voltage'></div></td></tr>";c+="</table>";$("#pgauge_yield").html(c);function b(){function d(f){UpdateMeters(f,a);if(gMt!=null){clearTimeout(gMt)}gMt=setTimeout(b,10000);if(globalWdtI!=null){clearTimeout(globalWdtI)}}function e(){UpdateMeters(false,a);if(gMt!=null){clearTimeout(gMt)}gMt=setTimeout(b,10000);if(globalWdtI!=null){clearTimeout(globalWdtI)}}globalWdtI=setTimeout(e,60000);$.ajaxQueue({url:"meters.xml",method:"GET",dataType:"xml",success:d,error:e,timeout:30000})}b();hready();banner_draw()}var iloadstate=0;var jsloadtimer=0;function iload(){var a;try{if(!iloadstate){a=$}else{a=has2mpp}}catch(c){}if(a!=undefined){iloadstate++;jsloadtimer=0;if(iloadstate>1){iready();return}}if(jsloadtimer==0){jsloadtimer=201;var b=document.createElement("script");b.type="text/javascript";if(!iloadstate){b.src="jquery.min.js"}else{b.src="js.js"}document.getElementById("head").appendChild(b)}jsloadtimer--;setTimeout(iload,100)}var globalWdtH;var gDt;function hready(){function a(){function c(d){UpdateEnergyProduction(d);if(gDt!=null){clearTimeout(gDt)}gDt=setTimeout(a,30000);if(globalWdtH!=null){clearTimeout(globalWdtH)}}function b(){if(gDt!=null){clearTimeout(gDt)}gDt=setTimeout(a,30000);if(globalWdtH!=null){clearTimeout(globalWdtH)}}globalWdtH=setTimeout(b,60000);$.ajaxQueue({url:"data.xml",method:"GET",dataType:"xml",success:c,error:b,timeout:30000})}a();fplot("#D","D",0);fplot("#W","W",1)};
  | </script>
  | </head>


</body>
</html><head id='head'>
		<title>EnaSolar Inverter</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="splash" content="Enasolar Inverter">
		<style type="text/css">body,td,input,select{font-family:Tahoma,Verdana,Arial,Helvetica,sans-serif;font-size:9pt}body{margin:0}table{margin:0;padding:0;border:0;border-collapse:collapse}td{white-space:nowrap;border:0;margin:0;padding:1px}td,th{display:table-cell;vertical-align:inherit}h2{margin:0;color:#73a13f;font-size:12pt;width:214px;height:23px}.style2{width:150px}td.Reading{width:100px;font-weight:bold;text-align:right}.graph_title{font-size:12pt;font-weight:bold;text-align:center;color:#73a13f}.graph_y_label{font-size:8pt;text-align:right;color:#73a13f}#menu{padding:0;margin:12px 0}#menu li{list-style:none outside none;height:28px}#menu li a{color:#fff;font-size:17px;font-weight:bold;text-decoration:none}#menu li a:hover{text-decoration:underline}.meter_reading{font-size:20pt;text-align:left;padding-left:25px}</style>	
		<script src="[//ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js](http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js)" type="text/javascript"></script>
		
		<script type="text/javascript">
var tiv="Enasolar-Garden";if(tiv!=""){document.title=tiv};
var globalWdtI;var gMt;function iready(){var a="3";var c="<br/><table style='width: 100%;' cellspacing='10px'>";c+="<tr><td>Utilisation:</td></tr>";c+="<tr><td><div class='meter_reading' id='utilisation'></div></td></tr>";c+="<tr><td>Output Power:</td></tr>";c+="<tr><td><div class='meter_reading' id='output_power'></div></td></tr>";if(has2mpp(a)){c+="<tr><td>Input Voltage 1:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage'></div></td></tr>";c+="<tr><td>Input Voltage 2:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage2'></div></td></tr>"}else{c+="<tr><td>Input Voltage:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage'></div></td></tr>"}c+="<tr><td>Output Voltage:</td></tr>";c+="<tr><td><div class='meter_reading' id='output_voltage'></div></td></tr>";c+="</table>";$("#pgauge_yield").html(c);function b(){function d(f){UpdateMeters(f,a);if(gMt!=null){clearTimeout(gMt)}gMt=setTimeout(b,10000);if(globalWdtI!=null){clearTimeout(globalWdtI)}}function e(){UpdateMeters(false,a);if(gMt!=null){clearTimeout(gMt)}gMt=setTimeout(b,10000);if(globalWdtI!=null){clearTimeout(globalWdtI)}}globalWdtI=setTimeout(e,60000);$.ajaxQueue({url:"meters.xml",method:"GET",dataType:"xml",success:d,error:e,timeout:30000})}b();hready();banner_draw()}var iloadstate=0;var jsloadtimer=0;function iload(){var a;try{if(!iloadstate){a=$}else{a=has2mpp}}catch(c){}if(a!=undefined){iloadstate++;jsloadtimer=0;if(iloadstate>1){iready();return}}if(jsloadtimer==0){jsloadtimer=201;var b=document.createElement("script");b.type="text/javascript";if(!iloadstate){b.src="jquery.min.js"}else{b.src="js.js"}document.getElementById("head").appendChild(b)}jsloadtimer--;setTimeout(iload,100)}var globalWdtH;var gDt;function hready(){function a(){function c(d){UpdateEnergyProduction(d);if(gDt!=null){clearTimeout(gDt)}gDt=setTimeout(a,30000);if(globalWdtH!=null){clearTimeout(globalWdtH)}}function b(){if(gDt!=null){clearTimeout(gDt)}gDt=setTimeout(a,30000);if(globalWdtH!=null){clearTimeout(globalWdtH)}}globalWdtH=setTimeout(b,60000);$.ajaxQueue({url:"data.xml",method:"GET",dataType:"xml",success:c,error:b,timeout:30000})}a();fplot("#D","D",0);fplot("#W","W",1)};
   		</script>
	</head>`

**Comment by geustace** [comment]
Hmm, the code has all been html-ified and is pretty much unreadable.
The line from the HEAD section I need is the line that starts with var tiv=
I just browse to the page then Right click and show source.  I am using Firefox but other browsers ought to do the same. 
![image](https://github.com/geustace/home-assistant-enasolar/assets/88570674/bf708744-1327-4051-81c8-c94a58e3a9f8)
Can you try to get all of this line for me.  If it doesnt exist my plan B is to just not error out and let you override the values I cant extract.

**Comment by bashers222** [comment]
Try this:

var tiv="Enasolar-Garden";if(tiv!=""){document.title=tiv};
var globalWdtI;var gMt;function iready(){var a="3";var c="<br/><table style='width: 100%;' cellspacing='10px'>";c+="<tr><td>Utilisation:</td></tr>";c+="<tr><td><div class='meter_reading' id='utilisation'></div></td></tr>";c+="<tr><td>Output Power:</td></tr>";c+="<tr><td><div class='meter_reading' id='output_power'></div></td></tr>";if(has2mpp(a)){c+="<tr><td>Input Voltage 1:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage'></div></td></tr>";c+="<tr><td>Input Voltage 2:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage2'></div></td></tr>"}else{c+="<tr><td>Input Voltage:</td></tr>";c+="<tr><td><div class='meter_reading' id='input_voltage'></div></td></tr>"}c+="<tr><td>Output Voltage:</td></tr>";c+="<tr><td><div class='meter_reading' id='output_voltage'></div></td></tr>";c+="</table>";$("#pgauge_yield").html(c);function b(){function d(f){UpdateMeters(f,a);if(gMt!=null){clearTimeout(gMt)}gMt=setTimeout(b,10000);if(globalWdtI!=null){clearTimeout(globalWdtI)}}function e(){UpdateMeters(false,a);if(gMt!=null){clearTimeout(gMt)}gMt=setTimeout(b,10000);if(globalWdtI!=null){clearTimeout(globalWdtI)}}globalWdtI=setTimeout(e,60000);$.ajaxQueue({url:"meters.xml",method:"GET",dataType:"xml",success:d,error:e,timeout:30000})}b();hready();banner_draw()}var iloadstate=0;var jsloadtimer=0;function iload(){var a;try{if(!iloadstate){a=$}else{a=has2mpp}}catch(c){}if(a!=undefined){iloadstate++;jsloadtimer=0;if(iloadstate>1){iready();return}}if(jsloadtimer==0){jsloadtimer=201;var b=document.createElement("script");b.type="text/javascript";if(!iloadstate){b.src="jquery.min.js"}else{b.src="js.js"}document.getElementById("head").appendChild(b)}jsloadtimer--;setTimeout(iload,100)}var globalWdtH;var gDt;function hready(){function a(){function c(d){UpdateEnergyProduction(d);if(gDt!=null){clearTimeout(gDt)}gDt=setTimeout(a,30000);if(globalWdtH!=null){clearTimeout(globalWdtH)}}function b(){if(gDt!=null){clearTimeout(gDt)}gDt=setTimeout(a,30000);if(globalWdtH!=null){clearTimeout(globalWdtH)}}globalWdtH=setTimeout(b,60000);$.ajaxQueue({url:"data.xml",method:"GET",dataType:"xml",success:c,error:b,timeout:30000})}a();fplot("#D","D",0);fplot("#W","W",1)};

**Comment by geustace** [comment]
The needed data would appear not to be available in version 21, so I have assigned some defaults which you can override. I have uploaded a new version of pyenasolar and the enasolar intergration. HACS should show that it can be updated.
